# Generated by Django 5.2.1 on 2025-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_oferta', models.BooleanField(default=False)),
                ('es_nuevo', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tu_tabla_productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
