# Generated by Django 5.2.1 on 2025-05-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accion', '0002_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
