# Generated by Django 5.2.1 on 2025-06-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accion', '0004_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_nuevo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_oferta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_anterior',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='rating',
        ),
        migrations.AddField(
            model_name='producto',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
