# Generated by Django 5.2 on 2025-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('gmail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('dependencia', models.CharField(max_length=255)),
            ],
        ),
    ]
